{"stats": {"errors": 1, "failures": 0, "passes": 1, "skipped": 0, "encoding": "UTF-8", "total": 2}, "results": [{"classname": "index_test:FieldElementTest", "name": "test_mul", "time": 0.00035071372985839844, "type": "success"}, {"classname": "index_test:FieldElementTest", "name": "test_pow", "time": 0.00013303756713867188, "type": "error", "errtype": "builtins.AttributeError", "message": "'int' object has no attribute 'num'", "tb": "Traceback (most recent call last):\n  File \"/opt/conda/lib/python3.6/unittest/case.py\", line 59, in testPartExecutor\n    yield\n  File \"/opt/conda/lib/python3.6/unittest/case.py\", line 605, in run\n    testMethod()\n  File \"/home/blake41/ecc-mul-pow-jsong-pb-sf-072618/test/index_test.py\", line 13, in test_pow\n    self.assertEqual(a**3, FieldElement(15, 31))\n  File \"/home/blake41/ecc-mul-pow-jsong-pb-sf-072618/index.ipynb\", line 65, in __pow__\n    ]\nAttributeError: 'int' object has no attribute 'num'\n"}]}